name: Deploy to Firebase Hosting on Push

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - run: flutter pub get

      - name: Create .env file
        run: |
          echo "KEY_GITHUB_API=${{ secrets.KEY_GITHUB_API }}" > .env
        env:
          KEY_GITHUB_API: ${{ secrets.KEY_GITHUB_API }}

      - run: flutter build web

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup Firebase Service Account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_A9A4D }}' > $HOME/firebase_service_account.json
        shell: bash

      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase_service_account.json
        run: firebase deploy --only hosting
